### PR TITLE
feat: Data-driven BMT proof tests

### PR DESCRIPTION
**Pull request by bvrooman**
Related issues:
- Closes https://github.com/FuelLabs/fuel-core/issues/687

### CODE REVIEW

**Comment by pixelcircuits** [comment]
Just curious, what made you use yaml files to test against vs just hardcoding values into the typescript? Is this standard practice in other repos? If the test failed, wouldn't it be hard to identify which data set caused the failure?

**Comment by bvrooman** [comment]
Good questions:

> Just curious, what made you use yaml files to test against vs just hardcoding values into the typescript? Is this standard practice in other repos? 

I opted for external yaml files over hardcoding the tests because we want to execute the same test suite against multiple Merkle tree implementations. For example, I am using the [same test suite](https://github.com/FuelLabs/fuel-merkle/pull/125) to test the Rust implementation in `fuel-merkle`. The idea is to make updating the test suite as easy as possible. We can generate the test suite as yaml files and copy them to each repository that implements the functionality. Similarly, in `fuel-specs,` we already specify a [test suite for SMT roots](https://github.com/FuelLabs/fuel-specs/tree/master/test_vectors/sparse_merkle_tree), and we can propagate changes to this specification test suite to any of our SMT implementations.

> If the test failed, wouldn't it be hard to identify which data set caused the failure?

Yes, that's true. That is an unfortunate artifact of the currently proposed test framework. Ideally, we would be able to generate separate tests for each test vector to communicate the failure back to us. As of now, we have to manually inspect the test with breakpoints or log statements when we encounter a failure. I think a data-driven test framework that generates a test per test vector (if such a framework already exists) would be a nice incremental improvement.

**Review by adlerjohn — APPROVED** [review]
utACK

**Review by simonr0204 — APPROVED** [review]

**Comment by bvrooman** [comment]
This PR is currently waiting on finalization of the test suite definition, set out in https://github.com/FuelLabs/fuel-merkle/pull/125. We are actively modifying the test suite here, so once that is stable, I will add the updated test files here for re-review and approval.

**Review by simonr0204 — APPROVED** [review]
LGTM. This gives me so much more confidence in the solidity Merkle library implementation. How hard would it be to make a fuzzer to generate a ton more yaml files and run them all ?

**Comment by bvrooman** [comment]
> LGTM. This gives me so much more confidence in the solidity Merkle library implementation. How hard would it be to make a fuzzer to generate a ton more yaml files and run them all ?

I haven't looked into that specifically, but I do not imagine it would be very difficult, at least for positive cases. We could generate a random N sized tree and generate proof tests for any or all indices n in N, and repeat! We can do this for other test types as well. If this is something you'd be interested in exploring further, we can certainly discuss that.

**Pull request merged**
