### PR TITLE
Update package name and version for publishing on NPM

### PR DESCRIPTION
**Pull request by pixelcircuits**
Is there anything else that needs to be done to publish to NPM?

### CODE REVIEW

**Review by adlerjohn — COMMENTED** [review]
The org `fuel-contracts` doesn't exist on npmjs.org. It would have to be added. I can do so if we agree on the org name.

**Comment by adlerjohn** [comment]
cc @simonr0204 thoughts on the org name?

**Comment by pixelcircuits** [comment]
We could also do something like `fuel-solidity` if we want to distinguish it from some future helper libraries for sway contracts. I'm thinking we have our own set of audited contracts for devs to use like how most people use openzeppelin contracts.

**Comment by simonr0204** [comment]
I think the library name carries all the necessary info (namely, a Merkle tree library written in Solidity). To me it makes sense for it to be in the same namespace as all the other Fuel stuff published to npm.  (so that's @FuelLabs ? )

**Comment by adlerjohn** [comment]
`fuellabs` is actually an account, not an org: https://www.npmjs.com/~fuellabs!

**Comment by adlerjohn** [comment]
So it looks like the options are:

1. `fuellabs`
2. `fuel-contracts`
3. `fuel-solidity`

?

**Comment by simonr0204** [comment]
So will there eventually be Sway libs published there too ? In which case, neither `solidity` nor `contracts` would be accurate.

**Comment by adlerjohn** [comment]
We could potentially have Sway libs there as well, though using NPM for anything related to Sway should probably be discouraged from the get-go. So looks like `fuellabs` is the most generic?

**Comment by pixelcircuits** [comment]
The typescript team is already using `@fuel-ts`. That's what made me suggest `@fuel-contracts`. `@fuel-contracts` could be shared with sway code, if we make this package name `@fuel-contracts/merkle-sol` to denote that it's solidity

**Review by adlerjohn — APPROVED** [review]

**Pull request merged**
